### ISSUE TITLE
No icon to block overlays on FF39+ ?

### ISSUE THREAD

**Issue by Draky50110** [NicolaeNMV/BehindTheOverlay#13]
Hello

Just installed it and there is no icon to block overlays.
Even when I try to "customize" FF toolbar.

**Comment by NicolaeNMV** [comment]
Hi Darky,

What operating system do you use ?

I just tested on firefox 40, and I see the icon just fine.

I think I already saw a problem like before, but I'm not sure how to reproduce it.

I'll leave this link here https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars

<img width="823" alt="screen shot 2015-08-12 at 12 50 41" src="https://cloud.githubusercontent.com/assets/224201/9222256/86f36698-40f0-11e5-8ac3-ddc76726d8fc.png">

**Comment by Draky50110** [comment]
I'm using FF40 on WinXP @ work so I'll try @home in a couple of hours and let you know.

**Comment by Draky50110** [comment]
Solved : working perfectly in Win7.
So... not compatible XP maybe...

**Comment by NicolaeNMV** [comment]
What resolution of the screen do you have on XP ? One time I saw it not working was when a friend of mine had a large screen resolution.

**Comment by Draky50110** [comment]
Back on oldie : my XP screen is 1024x768 (4/3)...
