### ISSUE TITLE
no overlay found on pinterest

### ISSUE THREAD

**Issue by dennyhalim** [NicolaeNMV/BehindTheOverlay#19]
https://www.pinterest.com/explore/bible-verses/
ctrl+shift+x gives me 'no overlay has been found on this website'

so far, other sites works ok.
thanks!

**Comment by nitrocode** [comment]
Looks similar to #11

**Comment by CGjupoulton** [comment]
This is no longer true, I suggest closing this issue

**Comment by NicolaeNMV** [comment]
Looks like pinterest is now no longer showing an overlay. Thanks for opening the issue anyway 👍
