### ISSUE TITLE
Create keyboard shortcut to activate the extension

### ISSUE THREAD

**Issue by NicolaeNMV** [NicolaeNMV/BehindTheOverlay#2]
Inspect the used shortcuts to find an appropriate one.

**Comment by sidml** [comment]
Can anyone confirm that `Ctrl+Shift+X (Windows/Linux)` works in Firefox. 
I am using `Firefox 108.0.2 (64-bit)` on Ubuntu and it doesn't seem to work.

**Comment by nicsms** [comment]
> Can anyone confirm that `Ctrl+Shift+X (Windows/Linux)` works in Firefox. I am using `Firefox 108.0.2 (64-bit)` on Ubuntu and it doesn't seem to work.

It's not working for me either in Firefox 113.0.1 (64-bit), windows 11. #
